# Class I - An introduction to Julia

*Los Alamos National Laboratory Grid Science Winter School, 2019*

Welcome! This tutorial will introduce you to the basics of Julia. In addition to this tutorial, there are lots of fantastic tutorials by JuliaComputing: [https://github.com/JuliaComputing/JuliaBoxTutorials](https://github.com/JuliaComputing/JuliaBoxTutorials).

## Jupyter notebooks

Before we start though, you're probably wondering what this Jupyter notebook thing is! (If you already know, feel free to skip down a few cells.)

Jupyer notebooks are a handy way of combining text (like this), as well as code, computational output, and plots. The notebook is divided into a linear sequence of cells (from top to bottom). 

**ACTION ITEM:** double click on this cell and fix this speiling mistake! Then press `[CTRL]+[ENTER]` to "run" the cell and observe the output. You can also click the `Run` button in the toolbar at the top.

Now that we have notebooks out of the way, on to Julia.

## Other Resources

This notebook is designed to provide a minimalist crash course in the basics of Julia.  The following resources provide a more comprehensive introduction to Julia,
* [Intro to Julia](https://youtu.be/r2d5NA7RHno)


## Basic Data Types

Integers

In [1]:
1 + -2

-1

In [2]:
typeof(1)

Int64

Floating point numbers

In [3]:
1.2 - 2.3

-1.0999999999999999

In [4]:
typeof(-1.1)

Float64

There are also some cool things like an irrational representation of π. To make π (and most other greek letters), type \pi and then press [TAB].

In [5]:
π

π = 3.1415926535897...

In [6]:
typeof(π)

Irrational{:π}

Julia has native support for complex numbers

In [7]:
2 + 3im

2 + 3im

In [8]:
typeof(2 + 3im)

Complex{Int64}

Double quotes are used for strings

In [9]:
"This is Julia"

"This is Julia"

In [10]:
typeof("This is Julia")

String

Unicode is fine in strings

In [11]:
"π is about 3.1415"

"π is about 3.1415"

Julia symbols provide a way to make human readable unique identifiers,

In [12]:
:my_id

:my_id

In [13]:
typeof(:my_id)

Symbol

## Arithmetic and Equality Testing

Julia is great for math

In [14]:
1 + 1

2

Even math involving complex numbers

In [15]:
(2 + 1im) * (1 - 2im)

4 - 3im

We can also write things like the following using √ (`\sqrt`)

In [16]:
sin(2π/3) == √3/2

false

Wait. What???

In [17]:
sin(2π/3) - √3/2

1.1102230246251565e-16

Let's try again using ≈ (`\approx`).

In [18]:
sin(2π/3) ≈ √3/2

true

Note that this time we used ≈ instead of `==`. That is because computers don't use real numbers. They use a discrete representation called *floating point*. If you aren't careful, this can throw up all manner of issues. For example:

In [19]:
1 + 1e-16 == 1

true

It even turns out that floating point numbers aren't associative!

In [20]:
(1 + 1e-16) - 1e-16 == 1 + (1e-16 - 1e-16)

false

## Vectors, Matrices and Arrays

Similar to Matlab, Julia has native support for vectors, matrices and tensors; all of which are represented by arrays of different dimensions.

Vectors are constructed by comma-separated elements surrounded by square brackets:

In [21]:
b = [5, 6]

2-element Array{Int64,1}:
 5
 6

Matrices can by constructed with spaces separating the columns, and semicolons separating the rows:

In [22]:
A = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

We can do linear algebra:

In [23]:
x = A \ b

2-element Array{Float64,1}:
 -4.0
  4.5

In [24]:
A * x

2-element Array{Float64,1}:
 5.0
 6.0

In [25]:
A * x == b

true

Note that when multiplying vectors and matrices, dimensions matter. For example, you can't multiply a vector by a vector:

In [26]:
b * b

MethodError: MethodError: no method matching *(::Array{Int64,1}, ::Array{Int64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502
  *(!Matched::LinearAlgebra.Adjoint{#s623,#s622} where #s622<:Union{DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, ReinterpretArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where #s623, ::Union{DenseArray{S,1}, ReinterpretArray{S,1,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{S,1,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{S,1,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) where {T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64}, S} at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/matmul.jl:98
  *(!Matched::LinearAlgebra.Adjoint{#s623,#s622} where #s622<:LinearAlgebra.AbstractTriangular where #s623, ::AbstractArray{T,1} where T) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/triangular.jl:1805
  ...

But multiplying transposes works:

In [27]:
@show b' * b
@show b * b';

b' * b = 61
b * b' = [25 30; 30 36]


## Tuples

Julia makes extensive use of a simple data structure called Tuples.  Tuples are immutable collections of values.

For example,

In [28]:
t = ("hello", 1.2, :foo)

("hello", 1.2, :foo)

In [29]:
typeof(t)

Tuple{String,Float64,Symbol}

Tuples can be accessed by index, similar to arrays,

In [30]:
t[2]

1.2

And can be "unpacked" like so,

In [31]:
a, b, c = t
b

1.2

The values can also be given names, which is a convenient way of making light-weight data structures.

In [32]:
t = (word="hello", num=1.2, sym=:foo)

(word = "hello", num = 1.2, sym = :foo)

Then values can be accessed using a dot syntax,

In [33]:
t.word

"hello"

## Dictionaries

Similar to Python, Julia has native support for dictionaries.  Dictionaries provide a very generic way of mapping keys to values.  For example, a map of integers to strings,

In [34]:
d1 = Dict(1 => "A", 2 => "B", 4 => "D")

Dict{Int64,String} with 3 entries:
  4 => "D"
  2 => "B"
  1 => "A"

Looking up a values uses the bracket syntax,

In [35]:
d1[2]

"B"

Dictionaries support non-integer keys and can mix data types,

In [36]:
Dict("A" => 1, "B" => 2.5, "D" => 2 - 3im)

Dict{String,Number} with 3 entries:
  "B" => 2.5
  "A" => 1
  "D" => 2-3im

Dictionaries can be nested

In [37]:
d2 = Dict("A" => 1, "B" => 2, "D" => Dict(:foo => 3, :bar => 4))

Dict{String,Any} with 3 entries:
  "B" => 2
  "A" => 1
  "D" => Dict(:bar=>4,:foo=>3)

In [38]:
d2["B"]

2

In [39]:
d2["D"][:foo]

3

## For-Each Loops

Julia has native support for for-each style loops with the syntax `for <value> in <collection> end`.

In [40]:
for i in 1:5
    println(i)
end

1
2
3
4
5


In [41]:
for i in [1.2, 2.3, 3.4, 4.5, 5.6]
    println(i)
end

1.2
2.3
3.4
4.5
5.6


This for-each loop also works with dictionaries.

In [42]:
for (key, value) in Dict("A" => 1, "B" => 2.5, "D" => 2 - 3im)
    println("$key: $value")
end

B: 2.5
A: 1
D: 2 - 3im


Note that in contrast to vector languages like Matlab and R, loops do not result in a significant performance degradation in Julia.

## Control Flow

Julia control flow is similar to Matlab, using the keywords `if-elseif-else-end`, and the logical operators `||` and `&&` for *or* and *and* respectively. 


In [43]:
i = 10
for i in 0:3:15
    if i < 5 
        println("$(i) is less than 5")
    elseif i < 10
        println("$(i) is less than 10")
    else
        if i == 10
            println("the value is 10")
        else
            println("$(i) is bigger than 10")
        end
    end
end

0 is less than 5
3 is less than 5
6 is less than 10
9 is less than 10
12 is bigger than 10
15 is bigger than 10


## Comprehensions

Similar to languages like Haskell and Python, Julia supports the use of simple loops in the construction of arrays and dictionaries, called comprehenions.

A list of increasing integers,

In [44]:
[i for i in 1:5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

Matrices can be built by including multiple indices,

In [45]:
[i*j for i in 1:5, j in 5:10]

5×6 Array{Int64,2}:
  5   6   7   8   9  10
 10  12  14  16  18  20
 15  18  21  24  27  30
 20  24  28  32  36  40
 25  30  35  40  45  50

Conditional statements can be used to filter out some values,

In [46]:
[i for i in 1:10 if i%2 == 1]

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

A similar syntax can be used for building dictionaries

In [47]:
Dict("$i" => i for i in 1:10 if i%2 == 1)

Dict{String,Int64} with 5 entries:
  "1" => 1
  "5" => 5
  "7" => 7
  "9" => 9
  "3" => 3

## Functions

A simple function is defined as follows,

In [48]:
function print_hello()
    println("hello")
end
print_hello()

hello


Arguments can be added to a function,

In [49]:
function print_it(x)
    println(x)
end
print_it("hello")
print_it(1.234)
print_it(:my_id)

hello
1.234
my_id


Optional keyword arguments are also possible 

In [50]:
function print_it(x; prefix="value:")
    println("$(prefix) $x")
end
print_it(1.234)
print_it(1.234, prefix="val:")

value: 1.234
val: 1.234


The keyword `return` is used to specify the return values of a function.

In [51]:
function mult(x; y=2.0)
    return x * y
end
mult(4.0)

8.0

In [52]:
mult(4.0, y=5.0)

20.0

## Other notes on types

Usually, specifing types is not required to use Julia.  However, it can be helpful to understand the basics of Julia types for debugging.

For example this list has a type of `Array{Int64,1}` indicating that it is a one dimensional array of integer values.

In [53]:
[1, 5, -2, 7]

4-element Array{Int64,1}:
  1
  5
 -2
  7

In this example, the decimal values lead to a one dimensional array of floating point values, i.e. `Array{Float64,1}`.  Notice that the integer `7` is promoted to a `Float64`, because all elements in the array need share a common type.

In [54]:
[1.0, 5.2, -2.1, 7]

4-element Array{Float64,1}:
  1.0
  5.2
 -2.1
  7.0

## Mutable vs immutable objects

Some types in Julia are *mutable*, which means you can change the values inside them. A good example is an array. You can modify the contents of an array without having to make a new array.

In contrast, types like `Float64` are *immutable*. You can't modify the contents of a `Float64`.

This is something to be aware of when passing types into functions. For example:

In [55]:
function mutability_example(mutable_type::Vector{Int}, immutable_type::Int)
    mutable_type[1] += 1
    immutable_type += 1
    return
end

mutable_type = [1, 2, 3]
immutable_type = 1

mutability_example(mutable_type, immutable_type)

println("mutable_type: $(mutable_type)")
println("immutable_type: $(immutable_type)")

mutable_type: [2, 2, 3]
immutable_type: 1


Because `Vector{Int}` is a mutable type, modifying the variable inside the function changed the value outside of the function. In constrast, the change to `immutable_type` didn't modify the value outside the function.

You can check mutability with the `isimmutable` function.

In [56]:
@show isimmutable([1, 2, 3])
@show isimmutable(1);

isimmutable([1, 2, 3]) = false
isimmutable(1) = true


# Why is Julia fast?

Answer: it compiles a different version of each function depending on the type of the arguments.

Corollary: put code inside functions!

In [57]:
foobar(x) = x + x

foobar (generic function with 1 method)

Calling `foobar` with an `Int64` compiles a method that calls `add_int`.

In [58]:
@code_warntype foobar(1)

Body::Int64
1 ─ %1 = (Base.add_int)(x, x)::Int64
└──      return %1


Calling `foobar` with a `Float64` compiles a method that calls `add_float`

In [59]:
@code_warntype foobar(1.0)

Body::Float64
1 ─ %1 = (Base.add_float)(x, x)::Float64
└──      return %1


## Using Packages and the Package Manager

No matter how wonderful Julia's base language is, at some point you will want to use an extension package.  Some of these are built-in, for example random number generation is available in the `Random` package in the standard library. These packages are loaded with the commands `using` and `import`.

In [60]:
using Random
[rand() for i in 1:10]

10-element Array{Float64,1}:
 0.44875597011769197
 0.8941697518328338 
 0.655952588806036  
 0.5879974270314483 
 0.10604798442182228
 0.9405618972701071 
 0.16545432411319871
 0.9641889726896145 
 0.12204518463858283
 0.5878392003752448 

The Package Manager is used to install packages that are not part of Julia's standard library.

For example the following can be used to install JuMP,
```
using Pkg
Pkg.add("JuMP")
```

For a complete list of registed Julia packages see the package listing at https://pkg.julialang.org/.

From time to you may wish to use a Julia package that is not registered.  In this case a git repository URL can be used to install the package.
```
using Pkg
Pkg.add("https://github.com/user-name/MyPackage.jl.git")
```

Note that for clarity this example uses the package manager `Pkg`.  Julia 1.0 includes an interactive package manager that can be accessed using `]`.  [This video](https://youtu.be/76KL8aSz0Sg) gives an overview of using the interactive package manager environment.

## HELP!

Julia 1.0 includes a help mode that can be accessed using `?`.  Entering any object (e.g. function, type, struct, ...) into the help mode will show its documentation, if any is available.




In [61]:
?+

search: +



```
+(x, y...)
```

Addition operator. `x+y+z+...` calls this function with all arguments, i.e. `+(x, y, z, ...)`.

# Examples

```jldoctest
julia> 1 + 20 + 4
25

julia> +(1, 20, 4)
25
```

---

```
dt::Date + t::Time -> DateTime
```

The addition of a `Date` with a `Time` produces a `DateTime`. The hour, minute, second, and millisecond parts of the `Time` are used along with the year, month, and day of the `Date` to create the new `DateTime`. Non-zero microseconds or nanoseconds in the `Time` type will result in an `InexactError` being thrown.


## Some Common Gotchas

### MethodError

A common error in Julia is `MethodError`, which indicates that the function is not defined for the given value.  For example, by default the `ceil` function is not defined for complex numbers.  The "closest candidates" list suggest some Julia types that the function is defined for.

In [62]:
ceil(1.2 + 2.3im)

MethodError: MethodError: no method matching ceil(::Complex{Float64})
Closest candidates are:
  ceil(!Matched::Type{BigInt}, !Matched::BigFloat) at mpfr.jl:314
  ceil(!Matched::Missing) at missing.jl:112
  ceil(!Matched::Missing, !Matched::Integer) at missing.jl:112
  ...

### Hard-global scope

Julia 1.0 changed the way variables are defined in global scopes (if you don't know what that means, it is basically everything that is not inside a function).

For new users, this created a lot of confusion. Luckily, IJulia notebooks contain a work-around; however, the REPL does not. 

For example, the code below works, but if you run it in the REPL you will get the error `UndefVarError: i not defined`.

In [63]:
i = 0
for j in 1:3
    i += 1
end
i

3

If you run into this error in the REPL, our advice is to wrap everything in a function. This "feature" will be fixed in a future Julia release.

In [64]:
function foo()
    i = 0
    for j in 1:3
        i += 1
    end
    i
end
foo()

3